//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Css.Wpf.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Css.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 自动隐藏 的本地化字符串。
        /// </summary>
        internal static string Anchorable_AutoHide {
            get {
                return ResourceManager.GetString("Anchorable_AutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动隐藏 的本地化字符串。
        /// </summary>
        internal static string Anchorable_BtnAutoHide_Hint {
            get {
                return ResourceManager.GetString("Anchorable_BtnAutoHide_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏 的本地化字符串。
        /// </summary>
        internal static string Anchorable_BtnClose_Hint {
            get {
                return ResourceManager.GetString("Anchorable_BtnClose_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口位置 的本地化字符串。
        /// </summary>
        internal static string Anchorable_CxMenu_Hint {
            get {
                return ResourceManager.GetString("Anchorable_CxMenu_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停靠 的本地化字符串。
        /// </summary>
        internal static string Anchorable_Dock {
            get {
                return ResourceManager.GetString("Anchorable_Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停靠成标签式文档 的本地化字符串。
        /// </summary>
        internal static string Anchorable_DockAsDocument {
            get {
                return ResourceManager.GetString("Anchorable_DockAsDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 漂浮 的本地化字符串。
        /// </summary>
        internal static string Anchorable_Float {
            get {
                return ResourceManager.GetString("Anchorable_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏 的本地化字符串。
        /// </summary>
        internal static string Anchorable_Hide {
            get {
                return ResourceManager.GetString("Anchorable_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string Document_Close {
            get {
                return ResourceManager.GetString("Document_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭所有标签 的本地化字符串。
        /// </summary>
        internal static string Document_CloseAll {
            get {
                return ResourceManager.GetString("Document_CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 留此，关闭其他 的本地化字符串。
        /// </summary>
        internal static string Document_CloseAllButThis {
            get {
                return ResourceManager.GetString("Document_CloseAllButThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口位置 的本地化字符串。
        /// </summary>
        internal static string Document_CxMenu_Hint {
            get {
                return ResourceManager.GetString("Document_CxMenu_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停靠成标签式文档 的本地化字符串。
        /// </summary>
        internal static string Document_DockAsDocument {
            get {
                return ResourceManager.GetString("Document_DockAsDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 漂浮 的本地化字符串。
        /// </summary>
        internal static string Document_Float {
            get {
                return ResourceManager.GetString("Document_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移到下一标签组 的本地化字符串。
        /// </summary>
        internal static string Document_MoveToNextTabGroup {
            get {
                return ResourceManager.GetString("Document_MoveToNextTabGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移到上一标签组 的本地化字符串。
        /// </summary>
        internal static string Document_MoveToPreviousTabGroup {
            get {
                return ResourceManager.GetString("Document_MoveToPreviousTabGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建水平标签组 的本地化字符串。
        /// </summary>
        internal static string Document_NewHorizontalTabGroup {
            get {
                return ResourceManager.GetString("Document_NewHorizontalTabGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建垂直标签组 的本地化字符串。
        /// </summary>
        internal static string Document_NewVerticalTabGroup {
            get {
                return ResourceManager.GetString("Document_NewVerticalTabGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加条件 的本地化字符串。
        /// </summary>
        internal static string Filter_AddCondition {
            get {
                return ResourceManager.GetString("Filter_AddCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加组 的本地化字符串。
        /// </summary>
        internal static string Filter_AddGroup {
            get {
                return ResourceManager.GetString("Filter_AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空子项 的本地化字符串。
        /// </summary>
        internal static string Filter_RemoveChildren {
            get {
                return ResourceManager.GetString("Filter_RemoveChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除条件 的本地化字符串。
        /// </summary>
        internal static string Filter_RemoveCondition {
            get {
                return ResourceManager.GetString("Filter_RemoveCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除组 的本地化字符串。
        /// </summary>
        internal static string Filter_RemoveGroup {
            get {
                return ResourceManager.GetString("Filter_RemoveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 開頭 的本地化字符串。
        /// </summary>
        internal static string Operation_BeginWith {
            get {
                return ResourceManager.GetString("Operation_BeginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 之間 的本地化字符串。
        /// </summary>
        internal static string Operation_Between {
            get {
                return ResourceManager.GetString("Operation_Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含 的本地化字符串。
        /// </summary>
        internal static string Operation_Contain {
            get {
                return ResourceManager.GetString("Operation_Contain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 結尾 的本地化字符串。
        /// </summary>
        internal static string Operation_EndWith {
            get {
                return ResourceManager.GetString("Operation_EndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等於 的本地化字符串。
        /// </summary>
        internal static string Operation_Equal {
            get {
                return ResourceManager.GetString("Operation_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大於 的本地化字符串。
        /// </summary>
        internal static string Operation_Greater {
            get {
                return ResourceManager.GetString("Operation_Greater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大於等於 的本地化字符串。
        /// </summary>
        internal static string Operation_GreaterOrEqual {
            get {
                return ResourceManager.GetString("Operation_GreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 假值 的本地化字符串。
        /// </summary>
        internal static string Operation_IsFalse {
            get {
                return ResourceManager.GetString("Operation_IsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 為空 的本地化字符串。
        /// </summary>
        internal static string Operation_IsNull {
            get {
                return ResourceManager.GetString("Operation_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 真值 的本地化字符串。
        /// </summary>
        internal static string Operation_IsTrue {
            get {
                return ResourceManager.GetString("Operation_IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小於 的本地化字符串。
        /// </summary>
        internal static string Operation_Lesser {
            get {
                return ResourceManager.GetString("Operation_Lesser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小于等於 的本地化字符串。
        /// </summary>
        internal static string Operation_LesserOrEqual {
            get {
                return ResourceManager.GetString("Operation_LesserOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 之外 的本地化字符串。
        /// </summary>
        internal static string Operation_NotBetween {
            get {
                return ResourceManager.GetString("Operation_NotBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不包含 的本地化字符串。
        /// </summary>
        internal static string Operation_NotContain {
            get {
                return ResourceManager.GetString("Operation_NotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不等於 的本地化字符串。
        /// </summary>
        internal static string Operation_NotEqual {
            get {
                return ResourceManager.GetString("Operation_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不為空 的本地化字符串。
        /// </summary>
        internal static string Operation_NotNull {
            get {
                return ResourceManager.GetString("Operation_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每页: 的本地化字符串。
        /// </summary>
        internal static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复表头默认设置 的本地化字符串。
        /// </summary>
        internal static string ResetDataGridColumn {
            get {
                return ResourceManager.GetString("ResetDataGridColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认恢复表头默认设置？ 的本地化字符串。
        /// </summary>
        internal static string ResetDataGridColumnConfirmation {
            get {
                return ResourceManager.GetString("ResetDataGridColumnConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共 {0} 条记录 的本地化字符串。
        /// </summary>
        internal static string TotalRecords {
            get {
                return ResourceManager.GetString("TotalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大化 的本地化字符串。
        /// </summary>
        internal static string Window_Maximize {
            get {
                return ResourceManager.GetString("Window_Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复 的本地化字符串。
        /// </summary>
        internal static string Window_Restore {
            get {
                return ResourceManager.GetString("Window_Restore", resourceCulture);
            }
        }
    }
}
